name: Synchronize to forked repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: main # 동기화하고 싶은 브랜치명

      - name: Add remote-url
        run: |
          git remote add forked-repo https://99andrew99:${{ secrets.AUTO_ACTIONS }}@github.com/99andrew99/CoursePalette_FE
          git config user.name 99andrew99
          git config user.email ${{ secrets.EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main  # 동기화하고 싶은 브랜치명

      - name: Clean up
        run: |
          git remote remove forked-repo
